# Generated by Django 4.1.1 on 2022-09-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_movies_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
