# Generated by Django 4.1.1 on 2022-09-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_watcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_movie', to='main.movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_cat', to='main.category'),
        ),
        migrations.CreateModel(
            name='WatchMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movie', to='main.movies')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_watcher', to='main.watcher')),
            ],
        ),
    ]
