# Generated by Django 4.1.1 on 2022-09-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_entry_movie_alter_movies_category_watchmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main.user'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_cat', to='main.category'),
        ),
    ]
