# Generated by Django 4.1.1 on 2022-09-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_movies_auther_movierating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.watcher'),
        ),
    ]
