# Generated by Django 4.1.1 on 2022-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_movierating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchmovies',
            name='watcher',
        ),
        migrations.AddField(
            model_name='watchmovies',
            name='watcher',
            field=models.ManyToManyField(related_name='watched_watcher', to='main.watcher'),
        ),
    ]
