# Generated by Django 4.1.1 on 2022-10-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_movies_watcher_delete_watchmovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movie', to='main.movies')),
                ('watcher', models.ManyToManyField(related_name='watched_watcher', to='main.watcher')),
            ],
        ),
    ]
